name: BlazorGames
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Build with dotnet
      run: dotnet publish --configuration Release
#create Blazor WebAssembly dist output folder in the project directory
    - name: Install rsync 📚
      run: |
        apt-get update && apt-get install -y rsync
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER:  build/wwwroot  
